import type { ChangelogEntry } from './index';

export default {
  date: '2026-09-27',
  title: 'Fix generated images disappearing for your teammates',
  items: [
    'Images and videos generated by one person on your team are now visible to everyone on the team, on the canvas and in Media — not only to whoever generated them.'
  ]
} satisfies ChangelogEntry;
